import os
from sivo import Sivo
from sivo.core.config import ProjectConfig

# Get current directory
current_dir = os.path.dirname(os.path.abspath(__file__))
svg_path = os.path.join(current_dir, "annotated_template.svg")
# We will use a reliable remote placeholder image for the demonstration.
image_path = "https://picsum.photos/id/175/800/600"

def main():
    # 1. Load the blank, lightweight SVG template generated by `sivo annotate`
    # Sivo.from_svg is used for local file paths, from_template is for built-in templates.
    app = Sivo.from_svg(svg_path, theme="dark", lock_zoom_out=True)

    # 2. Add the original raster image natively into the SVG canvas.
    # This must be the SAME image you used in the annotator tool!
    # We use `insert_after="background"` to place it directly behind the interactive shapes.
    app.add_svg_background_image(image_path, insert_after="background", opacity=1.0)

    # 3. Map the transparent regions you drew in the annotator tool to interactive SIVO components
    app.map(
        "machine_a",
        tooltip="Main Extruder",
        color="#3b82f6",
        hover_color="#60a5fa",
        html="<h3>Main Extruder</h3><p>Status: Running<br>Temperature: 180°C<br>Output: 450 units/hr</p>"
    )

    app.map(
        "conveyor_1",
        tooltip="Primary Conveyor",
        color="#10b981",
        hover_color="#34d399",
        html="<h3>Primary Conveyor</h3><p>Speed: 1.2 m/s<br>Load: 85%</p>"
    )

    app.map(
        "generator_zone",
        tooltip="Backup Generator",
        color="#ef4444",
        hover_color="#f87171",
        html="<h3>Backup Generator</h3><p>Status: Standby<br>Fuel: 90%</p>"
    )

    # Generate the dashboard HTML bundle
    output_path = os.path.join(current_dir, "output.html")
    app.to_html(output_path)

    print(f"Generated dashboard at: {output_path}")

if __name__ == "__main__":
    main()